name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  extra_cache_key:
    description: additional context to be included in the final cache key
    required: false
runs:
  using: composite
  steps:
  - run: python -m pip install pre-commit
    shell: bash
  - run: python -m pip freeze --local
    shell: bash
  - id: cache
    uses: actions/cache@v5
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonLocation }}|${{ inputs.extra_cache_key }}|${{ hashFiles('.pre-commit-config.yaml') }}
      restore-keys: |
        pre-commit-3|${{ env.pythonLocation }}|${{ inputs.extra_cache_key }}|
  - run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
  - run: pre-commit gc
    shell: bash
    if: steps.cache.outputs.cache-hit != 'true'
